### ISSUE TITLE
Erro ao salvar CPF

### ISSUE THREAD

**Issue by OtavioCapila** [Furyforev3r/CPF-DB#1]
Fui salvar o cpf, e acabei com o dedo preso na panela de pressão, não recomendo
![image](https://github.com/Furyforev3r/CPF-DB/assets/29285724/52635052-eab6-4fa6-b99a-ed0a1264f461)

**Comment by pedroperegrinaa** [comment]
uda,hiofzh?f weh ifwd mfisdfhwdufdwfom dfsduhfm usfxh sdufo

**Comment by Furyforev3r** [comment]
VSF KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKJ

**Comment by OtavioCapila** [comment]
LGTM
